version: "3"
services:
  url-parser:
    container_name: "url-parser"
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
