version: "3"
services:
  zoo-app:
    container_name: "zoo-app"
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
